language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "12.12.0"
notifications:
  email: false
stages:
  - lint
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: dist
      name: build dist
      script: yarn build
    - stage: lint
      name: eslint
      script: npx eslint .
    - stage: lint
      name: commitlint
      before_script:
        - npm i -g @commitlint/travis-cli
      script: commitlint-travis
    - stage: deploy
      script: npx semantic-release